// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qyadjaahgiqkohvucfmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5YWRqYWFoZ2lxa29odnVjZm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjQ5MTcsImV4cCI6MjA2MzM0MDkxN30.KcdcadpSESh9EOMrvLKk8tgowY5VBfyLQYL9NfoaT5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);